In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

In [13]:
df=pd.read_csv('pokemon_complete_stats.csv')

In [14]:
df.head()

,id,name,height_dm,weight_hg,base_experience,type_1,type_2,hp,attack,defense,special_attack,special_defense,speed,abilities,generation,is_legendary,is_mythical,color,shape,capture_rate
0,1,bulbasaur,7,69,64.0,grass,poison,45,49,49,65,65,45,"overgrow, chlorophyll",generation-i,False,False,green,quadruped,45
1,2,ivysaur,10,130,142.0,grass,poison,60,62,63,80,80,60,"overgrow, chlorophyll",generation-i,False,False,green,quadruped,45
2,3,venusaur,20,1000,236.0,grass,poison,80,82,83,100,100,80,"overgrow, chlorophyll",generation-i,False,False,green,quadruped,45
3,4,charmander,6,85,62.0,fire,NaN,39,52,43,60,50,65,"blaze, solar-power",generation-i,False,False,red,upright,45
4,5,charmeleon,11,190,142.0,fire,NaN,58,64,58,80,65,80,"blaze, solar-power",generation-i,False,False,red,upright,45

In [15]:
df.isnull().sum()

id                   0
name                 0
height_dm            0
weight_hg            0
base_experience     49
type_1               0
type_2             586
hp                   0
attack               0
defense              0
special_attack       0
special_defense      0
speed                0
abilities           14
generation           0
is_legendary         0
is_mythical          0
color                0
shape                0
capture_rate         0
dtype: int64

In [16]:
df['is_legendary'].unique()

array([False,  True])

In [17]:
df["color"].unique()

<StringArray>
[ 'green',    'red',   'blue',  'white',  'brown', 'yellow', 'purple',
   'pink',   'gray',  'black']
Length: 10, dtype: str

In [18]:
df["shape"].unique()

<StringArray>
['quadruped',   'upright',     'armor',  'squiggle', 'bug-wings',     'wings',
  'humanoid',      'legs',      'blob',     'heads', 'tentacles',      'arms',
      'fish',      'ball']
Length: 14, dtype: str

In [20]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

cols = ["is_legendary", "is_mythical", "color", "shape"]

encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

encoded = encoder.fit_transform(df[cols])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(cols),
    index=df.index
)

df = pd.concat(
    [df.drop(columns=cols), encoded_df],
    axis=1
)

df.head()

,id,name,height_dm,weight_hg,base_experience,type_1,type_2,hp,attack,defense,...,shape_bug-wings,shape_fish,shape_heads,shape_humanoid,shape_legs,shape_quadruped,shape_squiggle,shape_tentacles,shape_upright,shape_wings
0,1,bulbasaur,7,69,64.0,grass,poison,45,49,49,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,2,ivysaur,10,130,142.0,grass,poison,60,62,63,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,3,venusaur,20,1000,236.0,grass,poison,80,82,83,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,4,charmander,6,85,62.0,fire,NaN,39,52,43,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,5,charmeleon,11,190,142.0,fire,NaN,58,64,58,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [21]:
df.describe()

,id,height_dm,weight_hg,base_experience,hp,attack,defense,special_attack,special_defense,speed,...,shape_bug-wings,shape_fish,shape_heads,shape_humanoid,shape_legs,shape_quadruped,shape_squiggle,shape_tentacles,shape_upright,shape_wings
count,1351.000000,1351.000000,1351.000000,1302.000000,1351.000000,1351.000000,1351.000000,1351.000000,1351.000000,1351.000000,...,1351.000000,1351.000000,1351.000000,1351.000000,1351.000000,1351.000000,1351.000000,1351.000000,1351.000000,1351.000000
mean,2841.692080,20.443375,991.059956,161.943932,71.673575,82.757957,76.193930,75.418209,74.115470,72.000000,...,0.019245,0.046632,0.019245,0.148038,0.022206,0.204293,0.040711,0.019245,0.210215,0.082902
std,4139.019112,53.238467,1953.115812,82.532554,26.827529,32.351906,30.712902,34.026272,27.800826,30.642043,...,0.137436,0.210928,0.137436,0.355270,0.147407,0.403333,0.197692,0.137436,0.407612,0.275835
min,1.000000,1.000000,0.000000,36.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,338.500000,6.000000,94.500000,71.000000,55.000000,60.000000,55.000000,50.000000,54.000000,49.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,676.000000,11.000000,326.000000,165.000000,70.000000,80.000000,70.000000,69.000000,70.000000,70.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1013.500000,17.000000,853.500000,222.500000,85.000000,102.500000,95.000000,97.000000,90.000000,95.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,10326.000000,1000.000000,10000.000000,608.000000,255.000000,190.000000,250.000000,216.000000,250.000000,200.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [22]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

encoded = encoder.fit_transform(
    df[["type_1", "type_2"]]
)

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["type_1", "type_2"]),
    index=df.index
)

df = pd.concat(
    [df.drop(columns=["type_1", "type_2"]), encoded_df],
    axis=1
)

df.head()

,id,name,height_dm,weight_hg,base_experience,hp,attack,defense,special_attack,special_defense,...,type_2_grass,type_2_ground,type_2_ice,type_2_normal,type_2_poison,type_2_psychic,type_2_rock,type_2_steel,type_2_water,type_2_nan
0,1,bulbasaur,7,69,64.0,45,49,49,65,65,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,ivysaur,10,130,142.0,60,62,63,80,80,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3,venusaur,20,1000,236.0,80,82,83,100,100,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,4,charmander,6,85,62.0,39,52,43,60,50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,charmeleon,11,190,142.0,58,64,58,80,65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [23]:
df.isnull().sum()

id                  0
name                0
height_dm           0
weight_hg           0
base_experience    49
                   ..
type_2_psychic      0
type_2_rock         0
type_2_steel        0
type_2_water        0
type_2_nan          0
Length: 79, dtype: int64

In [27]:
df.fillna(df[["base_experience"]].mean(), inplace=True)

,id,name,height_dm,weight_hg,base_experience,hp,attack,defense,special_attack,special_defense,...,type_2_grass,type_2_ground,type_2_ice,type_2_normal,type_2_poison,type_2_psychic,type_2_rock,type_2_steel,type_2_water,type_2_nan
0,1,bulbasaur,7,69,64.000000,45,49,49,65,65,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,ivysaur,10,130,142.000000,60,62,63,80,80,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3,venusaur,20,1000,236.000000,80,82,83,100,100,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,4,charmander,6,85,62.000000,39,52,43,60,50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,charmeleon,11,190,142.000000,58,64,58,80,65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1346,10322,tatsugiri-curly-mega,6,240,161.943932,68,65,90,135,125,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1347,10323,tatsugiri-droopy-mega,6,240,161.943932,68,65,90,135,125,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1348,10324,tatsugiri-stretchy-mega,6,240,161.943932,68,65,90,135,125,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1349,10325,baxcalibur-mega,21,3150,161.943932,115,175,117,105,101,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1350,10326,meowstic-female-mega,8,101,161.943932,74,48,76,143,101,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [28]:
df.isnull().sum()

id                 0
name               0
height_dm          0
weight_hg          0
base_experience    0
                  ..
type_2_psychic     0
type_2_rock        0
type_2_steel       0
type_2_water       0
type_2_nan         0
Length: 79, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["id", "name"])
y = df["name"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [30]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1080, 77), (271, 77), (1080,), (271,))

In [32]:
y_train

756                  salandit
109                   weezing
1027             deoxys-speed
549      basculin-red-striped
486          giratina-altered
                ...
1095             slowbro-mega
1130            dugtrio-alola
1294    miraidon-aquatic-mode
860                grimmsnarl
1126          sandslash-alola
Name: name, Length: 1080, dtype: str

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

ValueError: could not convert string to float: 'corrosion, oblivious'